export const CatalogoAreasNiveles = {
  "Astronomía-Astrofísica": [
    { nombre: "1P", desde: "1ro Primaria", hasta: "1ro Primaria" },
    { nombre: "2P", desde: "2do Primaria", hasta: "2do Primaria" },
    { nombre: "3P", desde: "3ro Primaria", hasta: "3ro Primaria" },
    { nombre: "4P", desde: "4to Primaria", hasta: "4to Primaria" },
    { nombre: "5P", desde: "5to Primaria", hasta: "5to Primaria" },
    { nombre: "6P", desde: "6to Primaria", hasta: "6to Primaria" },
    { nombre: "1S", desde: "1ro Secundaria", hasta: "1ro Secundaria" },
    { nombre: "2S", desde: "2do Secundaria", hasta: "2do Secundaria" },
    { nombre: "3S", desde: "3ro Secundaria", hasta: "3ro Secundaria" },
    { nombre: "4S", desde: "4to Secundaria", hasta: "4to Secundaria" },
    { nombre: "5S", desde: "5to Secundaria", hasta: "5to Secundaria" },
    { nombre: "6S", desde: "6to Secundaria", hasta: "6to Secundaria" }
  ],
  "Biología": [
    { nombre: "1P", desde: "1ro Primaria", hasta: "1ro Primaria" },
    { nombre: "2P", desde: "2do Primaria", hasta: "2do Primaria" },
    { nombre: "3P", desde: "3ro Primaria", hasta: "3ro Primaria" },
    { nombre: "4P", desde: "4to Primaria", hasta: "4to Primaria" },
    { nombre: "5P", desde: "5to Primaria", hasta: "5to Primaria" },
    { nombre: "6P", desde: "6to Primaria", hasta: "6to Primaria" },
    { nombre: "1S", desde: "1ro Secundaria", hasta: "1ro Secundaria" },
    { nombre: "2S", desde: "2do Secundaria", hasta: "2do Secundaria" },
    { nombre: "3S", desde: "3ro Secundaria", hasta: "3ro Secundaria" },
    { nombre: "4S", desde: "4to Secundaria", hasta: "4to Secundaria" },
    { nombre: "5S", desde: "5to Secundaria", hasta: "5to Secundaria" },
    { nombre: "6S", desde: "6to Secundaria", hasta: "6to Secundaria" }
  ],
  "Física": [
    { nombre: "1P", desde: "1ro Primaria", hasta: "1ro Primaria" },
    { nombre: "2P", desde: "2do Primaria", hasta: "2do Primaria" },
    { nombre: "3P", desde: "3ro Primaria", hasta: "3ro Primaria" },
    { nombre: "4P", desde: "4to Primaria", hasta: "4to Primaria" },
    { nombre: "5P", desde: "5to Primaria", hasta: "5to Primaria" },
    { nombre: "6P", desde: "6to Primaria", hasta: "6to Primaria" },
    { nombre: "1S", desde: "1ro Secundaria", hasta: "1ro Secundaria" },
    { nombre: "2S", desde: "2do Secundaria", hasta: "2do Secundaria" },
    { nombre: "3S", desde: "3ro Secundaria", hasta: "3ro Secundaria" },
    { nombre: "4S", desde: "4to Secundaria", hasta: "4to Secundaria" },
    { nombre: "5S", desde: "5to Secundaria", hasta: "5to Secundaria" },
    { nombre: "6S", desde: "6to Secundaria", hasta: "6to Secundaria" }
  ],
  "Informática": [
    { nombre: "GUACAMAYO", desde: "5to Primaria", hasta: "6to Primaria" },
    { nombre: "GUANACO", desde: "1ro Secundaria", hasta: "3ro Secundaria" },
    { nombre: "LONDRA", desde: "1ro Secundaria", hasta: "3ro Secundaria" },
    { nombre: "JUCUMARI", desde: "4to Secundaria", hasta: "6to Secundaria" },
    { nombre: "BUFEO", desde: "1ro Secundaria", hasta: "3ro Secundaria" },
    { nombre: "PUMA", desde: "4to Secundaria", hasta: "6to Secundaria" }
  ],
  "Matemáticas": [
    { nombre: "PRIMER NIVEL", desde: "1ro Secundaria", hasta: "1ro Secundaria" },
    { nombre: "SEGUNDO NIVEL", desde: "2do Secundaria", hasta: "2do Secundaria" },
    { nombre: "TERCER NIVEL", desde: "3ro Secundaria", hasta: "3ro Secundaria" },
    { nombre: "CUARTO NIVEL", desde: "4to Secundaria", hasta: "4to Secundaria" },
    { nombre: "QUINTO NIVEL", desde: "5to Secundaria", hasta: "5to Secundaria" },
    { nombre: "SEXTO NIVEL", desde: "6to Secundaria", hasta: "6to Secundaria" }
  ],
  "Química": [
    { nombre: "1P", desde: "1ro Primaria", hasta: "1ro Primaria" },
    { nombre: "2P", desde: "2do Primaria", hasta: "2do Primaria" },
    { nombre: "3P", desde: "3ro Primaria", hasta: "3ro Primaria" },
    { nombre: "4P", desde: "4to Primaria", hasta: "4to Primaria" },
    { nombre: "5P", desde: "5to Primaria", hasta: "5to Primaria" },
    { nombre: "6P", desde: "6to Primaria", hasta: "6to Primaria" },
    { nombre: "1S", desde: "1ro Secundaria", hasta: "1ro Secundaria" },
    { nombre: "2S", desde: "2do Secundaria", hasta: "2do Secundaria" },
    { nombre: "3S", desde: "3ro Secundaria", hasta: "3ro Secundaria" },
    { nombre: "4S", desde: "4to Secundaria", hasta: "4to Secundaria" },
    { nombre: "5S", desde: "5to Secundaria", hasta: "5to Secundaria" },
    { nombre: "6S", desde: "6to Secundaria", hasta: "6to Secundaria" }
  ],
  "Robótica": [
    { nombre: "BUILDERS P", desde: "5to Primaria", hasta: "6to Primaria" },
    { nombre: "BUILDERS S", desde: "1ro Secundaria", hasta: "6to Secundaria" },
    { nombre: "LEGO P", desde: "5to Primaria", hasta: "6to Primaria" },
    { nombre: "LEGO S", desde: "1ro Secundaria", hasta: "6to Secundaria" }
  ]
};

export const categoriasPredefinidasMap = {
  "1P": { nombre: "1P", desde: "1ro Primaria", hasta: "1ro Primaria" },
  "2P": { nombre: "2P", desde: "2do Primaria", hasta: "2do Primaria" },
  "3P": { nombre: "3P", desde: "3ro Primaria", hasta: "3ro Primaria" },
  "4P": { nombre: "4P", desde: "4to Primaria", hasta: "4to Primaria" },
  "5P": { nombre: "5P", desde: "5to Primaria", hasta: "5to Primaria" },
  "6P": { nombre: "6P", desde: "6to Primaria", hasta: "6to Primaria" },
  "1S": { nombre: "1S", desde: "1ro Secundaria", hasta: "1ro Secundaria" },
  "2S": { nombre: "2S", desde: "2do Secundaria", hasta: "2do Secundaria" },
  "3S": { nombre: "3S", desde: "3ro Secundaria", hasta: "3ro Secundaria" },
  "4S": { nombre: "4S", desde: "4to Secundaria", hasta: "4to Secundaria" },
  "5S": { nombre: "5S", desde: "5to Secundaria", hasta: "5to Secundaria" },
  "6S": { nombre: "6S", desde: "6to Secundaria", hasta: "6to Secundaria" },
  "PRIMER NIVEL": { nombre: "PRIMER NIVEL", desde: "1ro Secundaria", hasta: "1ro Secundaria" },
  "SEGUNDO NIVEL": { nombre: "SEGUNDO NIVEL", desde: "2do Secundaria", hasta: "2do Secundaria" },
  "TERCER NIVEL": { nombre: "TERCER NIVEL", desde: "3ro Secundaria", hasta: "3ro Secundaria" },
  "CUARTO NIVEL": { nombre: "CUARTO NIVEL", desde: "4to Secundaria", hasta: "4to Secundaria" },
  "QUINTO NIVEL": { nombre: "QUINTO NIVEL", desde: "5to Secundaria", hasta: "5to Secundaria" },
  "SEXTO NIVEL": { nombre: "SEXTO NIVEL", desde: "6to Secundaria", hasta: "6to Secundaria" },
  "GUACAMAYO": { nombre: "GUACAMAYO", desde: "5to Primaria", hasta: "6to Primaria" },
  "GUANACO": { nombre: "GUANACO", desde: "1ro Secundaria", hasta: "3ro Secundaria" },
  "LONDRA": { nombre: "LONDRA", desde: "1ro Secundaria", hasta: "3ro Secundaria" },
  "JUCUMARI": { nombre: "JUCUMARI", desde: "4to Secundaria", hasta: "6to Secundaria" },
  "BUFEO": { nombre: "BUFEO", desde: "1ro Secundaria", hasta: "3ro Secundaria" },
  "PUMA": { nombre: "PUMA", desde: "4to Secundaria", hasta: "6to Secundaria" },
  "BUILDERS P": { nombre: "BUILDERS P", desde: "5to Primaria", hasta: "6to Primaria" },
  "BUILDERS S": { nombre: "BUILDERS S", desde: "1ro Secundaria", hasta: "6to Secundaria" },
  "LEGO P": { nombre: "LEGO P", desde: "5to Primaria", hasta: "6to Primaria" },
  "LEGO S": { nombre: "LEGO S", desde: "1ro Secundaria", hasta: "6to Secundaria" }
};